import { Provider } from '@/app/provider'
import type { Metadata } from "next";
import { SessionProvider } from 'next-auth/react'
import { Inter, Crete_Round, Work_Sans } from "next/font/google";
import "./globals.css";
import {ChildProps} from "@/types";

const inter = Inter({ subsets: ["latin"] });
const creteRound = Crete_Round({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-creteRound",
})
const workSans = Work_Sans({
  weight: ["500","600"],
  subsets: ["latin"],
  variable: "--font-workSans",
})

export const metadata: Metadata = {
  title: "EduPress",
  description: "Generated by ASK250",
};

function RootLayout({children}:ChildProps) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <Provider>
      {children}
    </Provider>
    </body>
    </html>
  );
}

export default RootLayout







